//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace BH.Adapter.XML.Custom
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class ImportExportRecord
    {

        private ImportExportRecordOpeningRec[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OpeningRec", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ImportExportRecordOpeningRec[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ImportExportRecordOpeningRec
    {

        private string openingTypeIndexField;

        private string descriptionField;

        private string locationBuildingPartIndexField;

        private string locationWallIndexField;

        private string locationRoofIndexField;

        private string orientationField;

        private string curtainTypeField;

        private string curtainClosedField;

        private string overhangRatioField;

        private string wideOverhangField;

        private string areaTypeField;

        private string areaScaleTypeField;

        private string areaField;

        private string areaRecCalculationField;

        private string roofLightsPitchField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OpeningTypeIndex
        {
            get
            {
                return this.openingTypeIndexField;
            }
            set
            {
                this.openingTypeIndexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LocationBuildingPartIndex
        {
            get
            {
                return this.locationBuildingPartIndexField;
            }
            set
            {
                this.locationBuildingPartIndexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LocationWallIndex
        {
            get
            {
                return this.locationWallIndexField;
            }
            set
            {
                this.locationWallIndexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LocationRoofIndex
        {
            get
            {
                return this.locationRoofIndexField;
            }
            set
            {
                this.locationRoofIndexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Orientation
        {
            get
            {
                return this.orientationField;
            }
            set
            {
                this.orientationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CurtainType
        {
            get
            {
                return this.curtainTypeField;
            }
            set
            {
                this.curtainTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CurtainClosed
        {
            get
            {
                return this.curtainClosedField;
            }
            set
            {
                this.curtainClosedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OverhangRatio
        {
            get
            {
                return this.overhangRatioField;
            }
            set
            {
                this.overhangRatioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WideOverhang
        {
            get
            {
                return this.wideOverhangField;
            }
            set
            {
                this.wideOverhangField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AreaType
        {
            get
            {
                return this.areaTypeField;
            }
            set
            {
                this.areaTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AreaScaleType
        {
            get
            {
                return this.areaScaleTypeField;
            }
            set
            {
                this.areaScaleTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Area
        {
            get
            {
                return this.areaField;
            }
            set
            {
                this.areaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AreaRecCalculation
        {
            get
            {
                return this.areaRecCalculationField;
            }
            set
            {
                this.areaRecCalculationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RoofLightsPitch
        {
            get
            {
                return this.roofLightsPitchField;
            }
            set
            {
                this.roofLightsPitchField = value;
            }
        }
    }
}